<a href="https://colab.research.google.com/github/Omayer-Ahmed/Food_Ordering_System/blob/main/Numpy_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy as np


why do we use Numpy? It is a library in python. Numpy is used to perform mathematical operation based on array

Difference between array and list

array contains same data type's values but list contains multiple data type's values

In [ ]:
import numpy as np

In [ ]:
#list convert into array
lis=[1,2,3,4]
arr= np.array(lis)
print(arr)

[1 2 3 4]


In [ ]:
type(arr)

numpy.ndarray

In [ ]:
arr.shape

(4,)

In [ ]:
#multiple list convert in an array
lis1=[1,2,3,4]
lis2=[5,6,7,8]
lis3=[9,10,11,12]

arr=np.array([lis1,lis2,lis3])
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
arr.shape

(3, 4)

In [ ]:
#reshape an array using reshape()
arr.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

one dimensional array access

In [ ]:
item=[1,2,3,4,5]
np.array(item)
item[4]
item[0]

1

two dimensional array access

In [ ]:
item=[[1,2,3,4],[4,3,2,1],[5,6,7,8],[8,7,6,5]]
arr=np.array(item)

In [ ]:
arr

array([[1, 2, 3, 4],
       [4, 3, 2, 1],
       [5, 6, 7, 8],
       [8, 7, 6, 5]])

In [ ]:
arr[:,:]

array([[1, 2, 3, 4],
       [4, 3, 2, 1],
       [5, 6, 7, 8],
       [8, 7, 6, 5]])

In [ ]:
arr[1:3,1:3]

array([[3, 2],
       [6, 7]])

In [ ]:
#access items
item[2][3]

8

In [ ]:
#access items
arr[1:,2:]

array([[2, 1],
       [7, 8],
       [6, 5]])

In [ ]:
arr[1:3,1:3]

array([[3, 2],
       [6, 7]])

In [ ]:
arr[0:,1:]

array([[2, 3, 4],
       [3, 2, 1],
       [6, 7, 8],
       [7, 6, 5]])

In [ ]:
#reshape the array
arr=arr.reshape(1,16)

In [ ]:
arr

array([[1, 2, 3, 4, 4, 3, 2, 1, 5, 6, 7, 8, 8, 7, 6, 5]])

In [ ]:
item=np.arange(0,16,step=1).reshape(4,4)

In [ ]:
item

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

linspace is used to evenly spaced in a specific inverval

In [ ]:
lin=np.linspace(0,10,5)

In [ ]:
lin

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [ ]:
lin=np.linspace(0,100,30)

In [ ]:
lin

array([  0.        ,   3.44827586,   6.89655172,  10.34482759,
        13.79310345,  17.24137931,  20.68965517,  24.13793103,
        27.5862069 ,  31.03448276,  34.48275862,  37.93103448,
        41.37931034,  44.82758621,  48.27586207,  51.72413793,
        55.17241379,  58.62068966,  62.06896552,  65.51724138,
        68.96551724,  72.4137931 ,  75.86206897,  79.31034483,
        82.75862069,  86.20689655,  89.65517241,  93.10344828,
        96.55172414, 100.        ])

In [ ]:
#change the array elements
item=[[1,2,3,4],[4,3,2,1],[5,6,7,8],[8,7,6,5]]
arr=np.array(item)
print(arr)

[[1 2 3 4]
 [4 3 2 1]
 [5 6 7 8]
 [8 7 6 5]]


In [ ]:
arr[3:,2:]=100

In [ ]:
print(arr)

[[  1   2   3   4]
 [  4   3   2   1]
 [  5   6   7   8]
 [  8   7 100 100]]


In [ ]:
arr[1:3,2:4]=200
print(arr)

[[  1   2   3   4]
 [  4   3 200 200]
 [  5   6 200 200]
 [  8   7 100 100]]


In [ ]:
#add 2 with array's every element
arr+2

array([[  3,   4,   5,   6],
       [  6,   5, 202, 202],
       [  7,   8, 202, 202],
       [ 10,   9, 102, 102]])

In [ ]:
#multiplication 3 with array's every element
arr*3

array([[  3,   6,   9,  12],
       [ 12,   9, 600, 600],
       [ 15,  18, 600, 600],
       [ 24,  21, 300, 300]])

In [ ]:
#division 2 with array's every element
arr/2

array([[  0.5,   1. ,   1.5,   2. ],
       [  2. ,   1.5, 100. , 100. ],
       [  2.5,   3. , 100. , 100. ],
       [  4. ,   3.5,  50. ,  50. ]])

In [ ]:
#use of condition to check array's elements
arr>10

array([[False, False, False, False],
       [False, False,  True,  True],
       [False, False,  True,  True],
       [False, False,  True,  True]])

In [ ]:
#print the exact elements that maintains this condition
arr[arr>10]

array([200, 200, 200, 200, 100, 100])

In [ ]:
#take two array and merge them

arr1=np.arange(1,17,step=1).reshape(4,4)
arr2=np.arange(17,33,step=1).reshape(4,4)

In [ ]:
print(arr1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [ ]:
print(arr2)

[[17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]]


In [ ]:
#add two array
arr1+arr2

array([[18, 20, 22, 24],
       [26, 28, 30, 32],
       [34, 36, 38, 40],
       [42, 44, 46, 48]])

In [ ]:
#multiplicaton two array
arr1*arr2

array([[ 17,  36,  57,  80],
       [105, 132, 161, 192],
       [225, 260, 297, 336],
       [377, 420, 465, 512]])

In [ ]:
#use of ones function
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
np.ones((3,4),dtype=float)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
#use of zeros function
np.zeros((4,3),dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

#random value generates using rand() function


In [ ]:
np.random.rand(3,3)

array([[0.56916303, 0.34904138, 0.22264739],
       [0.22787705, 0.81967185, 0.93339916],
       [0.65890009, 0.18335072, 0.41617086]])

In [ ]:
#it is used in normal distribution of matplot
np.random.randn(4,4)

array([[-0.45124174,  0.43513844,  0.41195969,  0.28352086],
       [ 1.0712837 , -0.09442971, -0.02665119, -0.5631201 ],
       [ 1.06859365,  0.240705  , -0.9047741 , -0.34151403],
       [ 1.97134062, -0.10203838,  1.77565513, -0.60865913]])